spring:
  application:
    name: tweetservice
    
amazon:
  access:
    key: 
  region: us-east-2
  end-point:
    url: dynamodb.us-east-2.amazonaws.com

server:
  port: 8095
logging:
  file:
    name: C:/805831_Chanthanu/Tweet_App_Component_2/Tweet_App_Component_2/MidTier/tweetLog.log
