spring:
  application:
    name: tweetservice
    
amazon:
  access:
    key:
    secret-key:
  region:
  end-point:
    url: dynamodb.us-east-1.amazonaws.com

server:
  port: 8095
logging:
  file:
    name: C:/805831_Chanthanu/Tweet_App_Component_2/Tweet_App_Component_2/MidTier/tweetLog.log